### ISSUE TITLE
Endpoint de Contato

### ISSUE THREAD

**Issue by v1d3rm3** [ccsa-ufrn/seminario-ccsa-old#4]
Endpoint, com método `post`, para cadastrar um mensagem de contato do usuário. Serão enviados os seguintes dados via método post em formato **JSON**, para o Endpoint:

```json
{
    "name": "nome do usuário",
    "email": "email do usuário",
    "subject": "assunto da mensagem do usuário",
    "message": "mensagem do usuário",
}
```

A resposta do servidor deve ser com `status 200` e retorna o objeto cadastrado, caso a mensagem tenha sido enviada com sucesso. Caso contrário, retornar um `status` de acordo com a lista de códigos https://en.wikipedia.org/wiki/List_of_HTTP_status_codes, e um campo mensagem informando o erro detalhado.

Ex.:

```json
{
   "message": "campos obrigatórios não preenchidos."
}
```

**Comment by mrmorais** [comment]
Atualizei um campo de 'mail' => 'email' para ficar de acordo com a tabela no banco de dados

**Comment by v1d3rm3** [comment]
Verdade, valeu!

**Comment by mrmorais** [comment]
Fechando a issue
